### ISSUE TITLE
Scrum Masters doesn't usually vote.

### ISSUE THREAD

**Issue by ritchefelix** [dgurkaynak/slack-poker-planner#16]
I facilitate all our planning poker sessions and I never vote. Is there a way that I will not be asked to vote? If bug #14 is implemented, it will be tedious to use "/pp task @user1 @user2... @userN" every time if I don't want to be included in the voting. Maybe implement a flag for SM not voting?

**Comment by dgurkaynak** [comment]
Hmm, that's a tough one. Implementing some kind of a flag or a config for this will require great effort since this app is extremely simple, and I'm not keen on implementing a user-based configuration system. 

After fixing #14, I think that the best bet is creating a custom user group for the voters, so that you can use like `/pp task @usergroup`.

**Comment by dgurkaynak** [comment]
Issue #14 is just fixed & deployed. While working on it, I've discovered a weird & hacky workaround that can be useful for your situation. You can set your slack status as `away`, so when you use `/pp task` without any explicit mentions (which defaults to `@here` mention), poker planner bot won't detect & add you as a participant.

![image](https://user-images.githubusercontent.com/1475786/80005308-12185200-84cc-11ea-91d5-2fd2f405e188.png)

**Comment by ritchefelix** [comment]
That's a good work around. I can ask those who will not be voting to set themselves as away.

Right now, I click reveal when everyone that needs to vote has voted. It's not that much of a problem but I appreciate the effort on trying to find a solution.

BTW, this app is great and very useful!!!
