### ISSUE TITLE
Topics expire too quickly

### ISSUE THREAD

**Issue by leahkoerper** [dgurkaynak/slack-poker-planner#17]
My team is spread across timezones and we were really hoping that this app would let us do a lot of asynchronous planning poker via Slack. However, the polls apparently expire at some point, which means we end up with some of the team locked out of voting and I am unable to reveal the results we did get. I would like to be able to have topics not expire, or at least I would like to know what the expiration time frame is so I can plan around it.

**Comment by dgurkaynak** [comment]
Actually, there is no explicit expiration duration. However, this app is so simple that poker planning sessions are not persisted at all 😅  All the sessions are living in the memory, so that all the data is gone when the server or process is restarted etc. I'm assuming that you get `Ooops, could not find that topic, it may be expired` error after some time, right?

If so, I'm adding `enhancement` label to this issue. If there are enough requests, we can implement some kind of persistence for sessions.

**Comment by leahkoerper** [comment]
Yes, that's the message we're getting! Thanks for clarifying.

**Comment by spmiller** [comment]
Since we're all working from home, we've found this tool to be an almost perfect way of getting estimations. Thanks for your hard work, @dgurkaynak!

> If there are enough requests, we can implement some kind of persistence for sessions.
We're also seeing this message in our team too. Can we help to implement this? We'd need some pointers on where the session could/should be stored as we don't have experience writing a slack app, but we would love to help out.

**Comment by dgurkaynak** [comment]
@leahkoerper @spmiller I've just shipped [a big release](https://github.com/dgurkaynak/slack-poker-planner/releases/tag/1.0.0-beta.2). The sessions are now persisted for 48 hours. So I'm closing this issue, let me know you guys need anything.

**Comment by spmiller** [comment]
Thanks for your hard work @dgurkaynak!

**Comment by marcglobality** [comment]
Hi @dgurkaynak , the 48h is still too fast for us. Could be increased to one week? I guess now that you have the 48h should be just changing a value and would help us a lot. Thanks!

**Comment by dgurkaynak** [comment]
@marcglobality I've just changed it to 7 days. However, I don't want to guarantee the persistence of this change, since I don't know how much storage it will cost to my server. If I change it back, I'll let you know. But until that happens, newly created sessions are now persisted for 7 days 👍

**Comment by marcglobality** [comment]
great, thank you so much! 🙌
