### ISSUE TITLE
Reviled votes are not sorted by numerical order

### ISSUE THREAD

**Issue by MattBodey** [dgurkaynak/slack-poker-planner#28]
Currently, points are sorted by js string sort when revealing results. This means that points are sometimes shown in a non-logical order. 

Example: 

Given the points: 1, 2, 3, 5, 8, 13, 20, ☕ 

On the reveal screen, this would show in the following order (assuming all have votes): 1, 13, 2, 20, 3, 5, 8, ☕ 

Expected behaviour: 

As most point scores are numerical. The sort function should attempt to sort as a number first, then as a string, this would result in the correct string ordering. 

As an alternate, it may be preferable to sort by votes? 

I would be happy to pick this up if you would like.

**Comment by tjp502** [comment]
Rather than sorting numerically, could it be sorted in the same order as the points themselves? So if someone wanted their points to be `one two three` they'd show in the results in that order.

**Comment by dgurkaynak** [comment]
I agree with @tjp502. When someone is setting custom points, I believe that they're sorting the points implicitly in their head. We should adhere to that order, which is also the same order of points located on the voting screen.

What do you say @MattBodey? If you still want to pick it up, I'd be more than happy 🙌 
Otherwise, I can look it up this weekend.

**Comment by MattBodey** [comment]
@dgurkaynak  I found some time this morning to give this a look. PR is up and I look forward to your feedback 🙏

**Comment by dgurkaynak** [comment]
Hey @MattBodey, I've just deployed the code, it's live now 🙌 
Thanks again for your contribution 👍
