### ISSUE TITLE
Auto-reveal the responses when they're about the be expired

### ISSUE THREAD

**Issue by mtp1376** [dgurkaynak/slack-poker-planner#60]
We had created a couple of messages for estimations, but unfortunately when we tried to reveal the estimations they were gone with the message
`Ooops, could not find the session, it may be expired or cancelled`

One workaround may be to auto-reveal the responses when they're about to be expired. Also, is there a reason why they have been expired? Is there a time limit for the estimation?

**Comment by dgurkaynak** [comment]
Hey @mtp1376, as stated in the [FAQ](https://deniz.co/slack-poker-planner/#faq), the time limit is currently 7 days. After that, it will be deleted from database. 

There is a time limit existing, because I don't want to maintain an ever-growing database since this is a free service. Sorry for the inconvenience. However you can always self-host and set the expiration limit astronomically high, [it's configurable](https://github.com/dgurkaynak/slack-poker-planner/blob/master/.env#L21-L22).

I'm closing this issue because it seems duplicate with #43. Please let me know if you need anything else.
